- Privacy (Is it private?)/Access and Control/Data control.yaml
> Fixes issue 23

- Ownership (Is it mine?)/Permanence/Functionality Over Time.yaml
> Fixes #20 #27 #29

- Security (Is it safe?)/Data security/Security over time.yaml
> Addresses issue #9

- Security (Is it safe?)/Data security/Security over time.yaml
Fixes issue [19](https://github.com/TheDigitalStandard/TheDigitalStandard/issues/19).
> To address issue #19

- Privacy (Is it private?)/Access and Control/Data control.yaml
This updated is relevant to this issue: 
https://github.com/TheDigitalStandard/TheDigitalStandard/issues/10
> Add an indicator for requesting anonymized user data

- Privacy (Is it private?)/Access and Control/Data control.yaml
Reverting for insufficient review - FWIW I support this addition.
> Revert "Add an indicator for requesting anonymized user data"

- Privacy (Is it private?)/Overreach - Collecting Too Much Data/Data collection.yaml
Changed wording for data collection and sensors for issue #83.
Fixes #83
> Update Data collection.yaml

- Privacy (Is it private?)/Third Party Tracking - Data Sharing/Data use.yaml
Cleaned up the language in this section and added indicator for third party naming
> Update Data use.yaml

- Ownership (Is it mine?)/Permanence/Process for terms of service enforcement.yaml
Change the criterion: "I know how, when, and why the company or organization unilaterally closes user accounts" with "I know how, when, and why the company or organization unilaterally closes user accounts and/or restricts access to services."
fixes issue #60
> Update Process for terms of service enforcement.yaml

- Privacy (Is it private?)/Access and Control/Data control.yaml
- Privacy (Is it private?)/Data retention/Data retention and deletion.yaml
Add criteria &c around affirmatively getting rid of unnecessary data.
Expand delete-at-deletion to include service going out of operation.
> Issues 73+24 retention

- Privacy (Is it private?)/Access and Control/Data control.yaml
- Privacy (Is it private?)/Data retention/Data retention and deletion.yaml
Reverts TheDigitalStandard/TheDigitalStandard#124
> Revert "Issues 73+24 retention"

- Privacy (Is it private?)/Overreach - Collecting Too Much Data/Minimal data collection.yaml
Expand collection minimization beyond data directly requested from individual to encompass passive data collection and collection from other sources.
> Update Minimal data collection.yaml

- Security (Is it safe?)/Data security/Security Oversight.yaml
Added stronger language for third parties ("processors") dealing with user data on behalf of a company.
Fixes #104
> Update Security Oversight.yaml

- Privacy (Is it private?)/Overreach - Collecting Too Much Data/Data benefits.yaml
Draft of language for adding investigation of app permissions and purpose of each type of user information.
Fixes #84
> Draft for app permissions

- Privacy (Is it private?)/Third Party Tracking - Data Sharing/Data use.yaml
Break "Data Use" into "Data Use" and "Data Sharing"
Introduce minimization concepts for both data use and data sharing.
Propose structure changes to the file format in comments.
> Issue 74 expand use and sharing

- Governance & Compliance (Are they good?)/Privacy Policy & Terms of Service/Terms of Service and Privacy Policy documents.yaml
Added language for policies and docs to be as visible and findable as possible on the internet.
Fixes #101
> Updated ToS/Policy visibility indicators

- Ownership (Is it mine?)/Right to Repair/Repair Accessibility.yaml
Added procedures for repairability.
Fixes #113
> Update Repair Accessibility.yaml

- Ownership (Is it mine?)/Permanence/Functionality Over Time.yaml
- Fixed a typo
- Added indicator for bug reporting
- Added generic procedure
Fixes #108
> Update Functionality Over Time.yaml

- Privacy (Is it private?)/Access and Control/Data control.yaml
Add "simply and at no cost" to "Users can obtain a copy of their information" per @ferdeline suggestion
> Update indicator in Data control.yaml

- Security (Is it safe?)/Build Quality/Best Build Practices.yaml
Draft for adding reproducibility to best practices section.
Fixes #111
> Draft for adding ideas from #111

- Security (Is it safe?)/Build Quality/Best Build Practices.yaml
- Security (Is it safe?)/Build Quality/Product stability.yaml
working with @cody-f on this now.
> de-duplicating indicators

- Privacy (Is it private?)/Access and Control/Data control.yaml
Work with Stephanie to clean text.
> Separate indicator

- Governance & Compliance (Are they good?)/Open/Open Source.yaml
- Governance & Compliance (Are they good?)/Privacy Policy & Terms of Service/Terms of Service and Privacy Policy documents.yaml
- Ownership (Is it mine?)/Permanence/Functionality Over Time.yaml
- Ownership (Is it mine?)/Right to Repair/Repair Accessibility.yaml
- Privacy (Is it private?)/Access and Control/Data control.yaml
- Privacy (Is it private?)/Overreach - Collecting Too Much Data/Minimal data collection.yaml
- README.md
- Security (Is it safe?)/Build Quality/Best Build Practices.yaml
- Security (Is it safe?)/User Safety/Personal safety.yaml
From #144  https://github.com/TheDigitalStandard/TheDigitalStandard/issues/144
Need @cody-f @billfitzg @benrito or @mrerecich to review for next relase.
> Adding indicator for personal safety

- evaluations/privacy/data-use.yaml
It looks fine in github but on the website the sentence is broken up into two bullet points. There might be other ways to fix this other than the one I suggest here.
> Extra line break

- evaluations/privacy/data-retention-and-deletion.yaml
> deidentified to de-identified

- evaluations/privacy/minimal-data-collection.yaml
> Changed 'other' to 'otherwise'?

- evaluations/security/authentication.yaml
I also see many sentences that have the period at the end and many that don't. Not sure if that needs to be changed to all having periods?
> Misspelling of "unrecognized"
